apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 1.0.4
    helm:
      releaseName: argo
      values: |
        fullnameOverride: argo
        singleNamespace: false
        workflow:
          serviceAccount:
            create: true
            name: argo-workflow
          rbac:
            create: true
        controller:
          workflowDefaults:
            spec:
              serviceAccountName: argo-workflow
        server:
          serviceAccount:
            create: true
            name: argo-server
          extraArgs:
          - --auth-mode=server
          serviceType: ClusterIP
        useStaticCredentials: false
        artifactRepository:
          archiveLogs: false
          s3:
            bucket: hybrid-workflows-eks-dev-artifacts
            region: eu-north-1
            endpoint: s3.eu-north-1.amazonaws.com
            keyFormat: artifacts/{{workflow.name}}/{{pod.name}}
            useSDKCreds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
