apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hybrid-workflows-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/PGpalt/hybrid-workflows-gitops.git
    targetRevision: main
    path: apps/hybrid-workflows-operator/overlays/eks-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hybrid-workflows-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
