apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/pgpalt/hybrid-workflows-operator
  newTag: sha-7165a14f3e7128d8d39ee1429b7a6a7fe124ab2d
patches:
- path: namespace.yaml
  target:
    kind: Namespace
    name: hybrid-workflows-operator-system
