apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/pgpalt/hybrid-workflows-operator
  newTag: sha-9046156ad29e2ac9b4e19e923c7da1a1767fbd35
patches:
- path: namespace.yaml
  target:
    kind: Namespace
    name: hybrid-workflows-operator-system
