apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/pgpalt/hybrid-workflows-operator
  newTag: sha-369885a4618e348aecefeb447aeee1a6a67c5d5b
patches:
- path: namespace.yaml
  target:
    kind: Namespace
    name: hybrid-workflows-operator-system
