apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-workflows-operator-controller-manager
  namespace: hybrid-workflows-operator-system
spec:
  template:
    spec:
      containers:
      - name: manager
        image: ghcr.io/pgpalt/hybrid-workflows-operator:sha-3892b9b9a1b58a5e985e184076cd6d07a7022408
        imagePullPolicy: Always
