apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-workflows-operator-controller-manager
  namespace: hybrid-workflows-operator-system
spec:
  template:
    spec:
      containers:
      - name: manager
        image: ghcr.io/pgpalt/hybrid-workflows-operator:sha-5e8b08478e20f28c854eda6767b547a1e147068f
        imagePullPolicy: Always
