apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/pgpalt/hybrid-workflows-operator
  newTag: sha-ce0671c85557a7c2ee9f4ac45c155e1fa1e3b096
patches:
- path: namespace.yaml
  target:
    kind: Namespace
    name: hybrid-workflows-operator-system
