apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/pgpalt/hybrid-workflows-operator
  newTag: sha-ecc61067912009cb766bf5111633c376353afe45
patches:
- path: namespace.yaml
  target:
    kind: Namespace
    name: hybrid-workflows-operator-system
