apiVersion: v1
kind: Secret
metadata:
  name: my-minio-cred
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  rootUser: minioadmin
  rootPassword: minioadmin123
  accesskey: minioadmin
  secretkey: minioadmin123
