apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/PGpalt/hybrid-workflows-gitops.git
    targetRevision: main
    path: platform/katib/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
