apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/PGpalt/hybrid-workflows-gitops.git
    targetRevision: main
    path: platform/katib/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: katib-webhook-cert
    namespace: kubeflow
    jsonPointers:
    - /data
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: katib.kubeflow.org
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: katib.kubeflow.org
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
