apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argo-namespace.yaml
- minio-credentials-secret.yaml
- application-minio.yaml
- application-katib.yaml
- application-argo-workflows.yaml
- application-argo-workflows-addons.yaml
