apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-controller-cluster-template
rules:
- apiGroups: ["argoproj.io"]
  resources: ["clusterworkflowtemplates"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-server-cluster-template
rules:
- apiGroups: ["argoproj.io"]
  resources: ["clusterworkflowtemplates"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cluster-template
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflow-controller-cluster-template
  apiGroup: rbac.authorization.k8s.io
